services:
  api:
    build:
      args:
        POETRY_INSTALL_EXTRA_ARGS: --with dev
      context: ./services/api/
    command: bash -c "alembic upgrade head && uvicorn src.app:app --proxy-headers --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./kiosk.db
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./services/api/:/app/
  frontend:
    build:
      context: ./services/frontend/
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
